---
- hosts: test
  user: vagrant
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - essentials
    - hostname
    - timezone
    - user
    - fail2ban
    - zsh
    - newrelic
    - ssh
    - ufw
